// scripts/generate-env.js
const fs = require('fs');
const path = require('path');
try { require('dotenv').config(); } catch (e) { /* dotenv opcional */ }

// buscar root del proyecto (donde está package.json)
function findProjectRoot(startDir) {
  let dir = startDir;
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, 'package.json'))) return dir;
    dir = path.dirname(dir);
  }
  return startDir;
}

const scriptDir = __dirname;
const projectRoot = findProjectRoot(scriptDir);
const outFile = path.join(projectRoot, 'src', 'environments', 'keys.ts');

const keys = {
  TMDB_ACCESS_TOKEN: process.env.TMDB_ACCESS_TOKEN || undefined,
  TMDB_API_KEY: process.env.TMDB_API_KEY || undefined
};

const content = `// AUTO-GENERATED by scripts/generate-env.js
// This file is gitignored. Do NOT commit your real keys.

export interface KeysEnv {
  TMDB_ACCESS_TOKEN?: string;
  TMDB_API_KEY?: string;
}

export const KEYS: KeysEnv = {
  TMDB_ACCESS_TOKEN: ${keys.TMDB_ACCESS_TOKEN ? JSON.stringify(String(keys.TMDB_ACCESS_TOKEN)) : 'undefined'},
  TMDB_API_KEY: ${keys.TMDB_API_KEY ? JSON.stringify(String(keys.TMDB_API_KEY)) : 'undefined'}
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, { encoding: 'utf8' });
console.log('[generate-env] wrote', outFile);
